# Generated by Django 4.2.4 on 2025-04-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_payment_validated',
        ),
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
